

DeliveryTruck.create!([
  {name: "Western Star", minimumPossibleWeight: nil, maximumPossibleWeight: nil, vinNumber: "5E0AZ1448CG343101", origin: "Atlanta, Ga", destination: "", yearManufactured: 2007, make: "Western", model: "Star", payloadEmptyWeight: nil, originLocation: "", currentLocation: "Atlanta, Ga", destinationLocation: "", weightCapacity: "80000", yearAquired: nil, carFax: "", maintenanceHistory: "", nextMaintenance: "", highwayMPG: nil, cityMPG: nil, avgMPG: 3.0, scheduledDepartureTime: "", estimatedArrivalTime: "", requestedArrivalTime: "", currentWeight: 72615.0, image: "img.jpeg"},
  {name: "International 7600", minimumPossibleWeight: nil, maximumPossibleWeight: nil, vinNumber: "1HTWYAHT69J108236", origin: "Seattle, Washington", destination: "", yearManufactured: 2009, make: "International", model: "7600", payloadEmptyWeight: nil, originLocation: "", currentLocation: "Seattle, Washington", destinationLocation: "", weightCapacity: "45000", yearAquired: nil, carFax: "", maintenanceHistory: "", nextMaintenance: "", highwayMPG: nil, cityMPG: nil, avgMPG: 6.0, scheduledDepartureTime: "", estimatedArrivalTime: "", requestedArrivalTime: "", currentWeight: 30327.0, image: "international.jpg"},
  {name: "INTERNATIONAL 7600 #2", minimumPossibleWeight: nil, maximumPossibleWeight: nil, vinNumber: "1HTWYAHT69J108237", origin: "Mobile, Alabama", destination: "", yearManufactured: 2009, make: "International", model: "7600", payloadEmptyWeight: nil, originLocation: "", currentLocation: "Mobile, Alabama", destinationLocation: "", weightCapacity: "45000", yearAquired: nil, carFax: "", maintenanceHistory: "", nextMaintenance: "", highwayMPG: nil, cityMPG: nil, avgMPG: 6.0, scheduledDepartureTime: "", estimatedArrivalTime: "", requestedArrivalTime: "", currentWeight: 42123.0, image: "international.jpg"}
])
Vehicle.create!([
  {name: "Ford Fusion", make: "Ford", model: "Fusion", yearManufactured: 2016, origin: "Tampa, Florida, United States", destination: "Boise, Idaho, United States", vinNumber: "9999F11111F", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 3553.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 2620.0, truckId: "2", image: "fusion.jpg"},
  {name: "Ford Bronco", make: "Ford", model: "Bronco", yearManufactured: 1987, origin: "Dallas, Texas, United States", destination: "Sunnydale, San Francisco, California, United States", vinNumber: "HDNOFS77734", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 4380.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 1687.0, truckId: "1", image: "bronco.jpg"},
  {name: "Tesla Roadster", make: "Tesla", model: "Roadster", yearManufactured: 2017, origin: "San Antonio, Texas, United States", destination: "Seattle, Washington, United States", vinNumber: "NJDKD443KKD", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 2877.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 2149.0, truckId: "3", image: "roadster.jpg"},
  {name: "Honda Prelude", make: "Honda", model: "Prelude", yearManufactured: 1991, origin: "Winder, GA, United States", destination: "Tulsa, OK, United States", vinNumber: "edkshannfsdfsfsd", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 2260.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 833.0, truckId: "2", image: "prelude.jpeg"},
  {name: "Honda Civic", make: "Honda", model: "Civic", yearManufactured: 1996, origin: "San Diego, California, United States", destination: "Las Vegas, Nevada, United States", vinNumber: "DJNEEO333D", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 2370.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 328.0, truckId: "nil", image: "Civic.jpg"},
  {name: "Mitsubishi Eclipse", make: "Mitsubishi", model: "Eclipse", yearManufactured: 1998, origin: "Salt Lake City, Utah, United States", destination: "Lakeland, Florida, United States", vinNumber: "JDNL3334MM", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 3005.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 2322.0, truckId: "1", image: "eclipse.jpg"},
  {name: "Hyundai Sonata", make: "Hyundai", model: "Sonata", yearManufactured: 2016, origin: "Brunswick, Georgia, United States", destination: "Montgomery, Alabama, United States", vinNumber: "JDDOOO30300", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 3430.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 262.0, truckId: "2", image: "sonata.png"},
  {name: "Cadillac Escalade", make: "Cadillac", model: "Escalade", yearManufactured: 2016, origin: "Brandon, Florida, United States", destination: "Portland, Oregon, United States", vinNumber: "MDMD0333D", minimumPossibleWeight: nil, maximumPossibleWeight: nil, actualWeight: 5430.0, origin_latitude: nil, origin_longitude: nil, destination_latitude: nil, destination_longitude: nil, distance: 3059.0, truckId: "2", image: "escalade.jpg"}
])
